__author__ = 'zats'

from wsgi.scrapers.telofun_scraper import TelofunScraper
from wsgi.scrapers.bay_area_bike_share_scraper import BayAreaBikeShareScraper
from wsgi.scrapers.bike_share_toronto_scraper import BikeShareTorontoScraper
from wsgi.scrapers.city_bike_new_york_scraper import CityBikeNewYorkScraper
from wsgi.scrapers.divvy_bikes_scraper import DivvyBikesScraper