#!/usr/bin/python
import os
import sys

try:
    import newrelic.agent

    config_file = os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'newrelic.ini')
    if os.path.exists(config_file):
        newrelic.agent.initialize(config_file, 'production')
except IOError:
    pass


sys.path.insert(0, os.path.dirname(__file__) or '.')

PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")

virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv, 'lib', os.environ['OPENSHIFT_PYTHON_VERSION'], 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    exec(open(virtualenv).read(), dict(__file__=virtualenv))
except IOError:
    pass

from bicycle import app as application
from bicycle import *
db.create_all()
