#!/bin/bash

echo "************ Cronny Started ***************"
date >> ${OPENSHIFT_DATA_DIR}/ticktock-start.log

source ${OPENSHIFT_HOMEDIR}/python/virtenv/bin/activate
python ${OPENSHIFT_REPO_DIR}/wsgi/crawler.py

echo "************ Cronny Executed ***************"
date >> ${OPENSHIFT_DATA_DIR}/ticktock-end.log